language: ruby
cache: bundler
sudo: false

script: ./script/test
after_success: ./script/deploy

env:
  global:
    secure: "QQRK8r/bp7FY8gDAPKywoiUkUSmW5gjrV4d1CM8IguncenjAy0HKGrOy0bWMLj0iz211AuxVvofk6c7B3410ILIjbGgMlPNFe8AGlZhL5lTIIc3D4SxEJ5t/cGQ/BCOyN+IG5qvgYBjwcRQm56NNOhwIHWYS6noAQOWfjafxL3I="
  matrix:
    - BUILD_SOURCE_GEM=1
    - VALIDATE_TRAVIS=1
    - SOURCE_VERSION="~>4.0.0"
    - SOURCE_VERSION="~>4.1.0"
    - SOURCE_VERSION="~>4.2.0"
    - SOURCE_VERSION="~>4.3.0"
    - SOURCE_VERSION="~>4.4.0"
    - SOURCE_VERSION="~>4.5.0"
    - SOURCE_VERSION="~>4.6.0"
    - SOURCE_VERSION="~>4.7.0"
    - SOURCE_VERSION="~>5.0.0"
    - SOURCE_VERSION="~>5.1.0"
    - SOURCE_VERSION="~>5.2.0"
    - SOURCE_VERSION="~>5.3.0"
    - SOURCE_VERSION="~>5.4.0"
    - SOURCE_VERSION="~>5.6.0"
    - SOURCE_VERSION="~>5.8.0"

matrix:
  include:
    - rvm: 2.0.0
      env:
    - rvm: 2.1
      env:
    - rvm: 2.2
      env:
    - rvm: 2.3.0
      env:
  allow_failures:
    - env: VALIDATE_TRAVIS=1
